name: WorkersAndWarriors
main: nmt.minecraft.WorkersAndWarriors.WorkersAndWarriorsPlugin
version: 1.00
permissions:
    WWAdmin:
        default: op
    WWPlayer:
        default: true
commands:
    ww:
        permission: WWAdmin
        usage: /ww <Command> <Args>
        description: This command is used to interact with plugin-level commands
    wwsession:
        permission: WWAdmin
        usage: /wwsession <Command> <Args>
        description: This command is used to interact with session-level commands
        aliases: wws
    wwplayer:
        permission: WWPlayer
        usage: /wwplayer <Command> <Args>
        description: This command is used to interact with WorkersAndWarriors' Player commands
        aliases: wwp
    wwteam:
        permission: WWAdmin
        usage: /wwteam <Command> <Args>
        description: This command sets up teams for a session.
        aliases: wwt